module.exports = {
    HTTP_STATUS_CODE : {
        SUCCESS : 200,
        UNAUTHORISED_ACCESS: 401,
        BAD_REQUEST: 400,
        PAYMENT_REQUIRED: 402,
        FORBIDDEN: 403,
        NOT_FOUND: 404,
        REQUEST_TIMEOUT: 408,
        INTERNAL_SERVER_ERROR: 500,
        NOT_IMPLEMENTED_ERROR: 501,
        BAD_GATEWAY: 502,
        SERVICE_UNAVAILABLE: 503,
        NETWORK_AUTHENTICATION_REQUIRED: 511
    }
};
